language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=2.7
    - python: 2.7
      env: TOXENV=check
    - python: 3.4
      env: TOXENV=3.4
    - python: 3.5
      env: TOXENV=3.5
    - python: pypy
      env: TOXENV=pypy
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
